### PR TITLE
[Fix #1981] Add discovery api hookup

### LINKED ISSUE #1981: Unable to deselect image when tapping center of the page.
Steps to reproduce
* On a blank page, add a toucan
* Move it so the top edge of the page
* Tap just beneath it on empty space on the page
* It doesn't deselect
* It should!

This only seems to happen in this specific position.

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

File: www_src/pages/discover/discover.jsx [hunk 1]
```diff
@@ -29,6 +43,8 @@ var Discover = React.createClass({
     return (
       <div id="discover">
         {cards}
+        <div hidden={this.state.loading || }>Sorry, no projects found.</div>
```
Comment (thisandagain) [inline www_src/pages/discover/discover.jsx]: I'm getting this error from webpack locally:
```bash
ERROR in ./www_src/pages/discover/discover.jsx
Module build failed: Error: Parse Error: Line 46: Unexpected token }
```

Comment (k88hudson) [inline www_src/pages/discover/discover.jsx]: oh wow lol. sorry

**Comment by thisandagain** [comment]
R+
