### PR TITLE
[Fix #1973] Fix loading issue on Make view

### LINKED ISSUE #1973: When I return to Make view from creating a new project, the page view is stuck loading
**Steps to reproduce**
* Create a new project
* Immediately go back to the Make view
* The Make view has a loading bar below the title
  * It doesn't go away
  * I can't create a new project or open an existing one while it's loading

Note: I can pull-to-refresh to get out of this state (but we're removing that from this view anyway)

### PR DESCRIPTION
**Pull request by k88hudson**
This is semi-critical

### CODE REVIEW

File: www_src/pages/make/make.jsx [hunk 1]
```diff
@@ -63,25 +63,22 @@ var Make = React.createClass({
...
-            id: body.project.id,
-            title: defaultTitle,
-            thumbnail: {},
-            // todo
-            author: userInfo
-          }].concat(this.state.projects)
-        });
       }
+      this.setState({
+        loading: false,
```
Comment (k88hudson) [inline www_src/pages/make/make.jsx]: this should happen in all cases, not just if Android doesn't exist

**Comment by thisandagain** [comment]
R+ :+1:
